/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LengkapiProfilRouteImport } from './routes/lengkapi-profil'
import { Route as IndexRouteImport } from './routes/index'

const LengkapiProfilRoute = LengkapiProfilRouteImport.update({
  id: '/lengkapi-profil',
  path: '/lengkapi-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lengkapi-profil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lengkapi-profil'
  id: '__root__' | '/' | '/lengkapi-profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LengkapiProfilRoute: typeof LengkapiProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lengkapi-profil': {
      id: '/lengkapi-profil'
      path: '/lengkapi-profil'
      fullPath: '/lengkapi-profil'
      preLoaderRoute: typeof LengkapiProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LengkapiProfilRoute: LengkapiProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
